name: Can npm publish action

description: GitHub Actions to check if it can be published to npm.

author: technote-space

inputs:
  PACKAGE_PATH:
    description: directory or pacakge.json path.
    required: false
  VERBOSE:
    description: Whether to show detail of errors.
    default: 'true'
    required: false

outputs:
  result:
    description: action result (passed or failed)

branding:
  icon: 'check-circle'
  color: 'green'

runs:
  using: node12
  main: lib/main.js
